# Generated by Django 5.2.6 on 2025-09-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('height_cm', models.IntegerField()),
                ('weight_kg', models.IntegerField()),
                ('activity_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
