# Generated by Django 5.2.6 on 2025-09-18 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kcal_per_100g', models.FloatField()),
                ('protein_g_per_100g', models.FloatField()),
                ('carb_g_per_100g', models.FloatField()),
                ('fat_g_per_100g', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁'), ('간식', '간식')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('kcal', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('carb_g', models.FloatField(blank=True, null=True)),
                ('fat_g', models.FloatField(blank=True, null=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intake.meal')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kcal_total', models.FloatField(default=0)),
                ('protein_total_g', models.FloatField(default=0)),
                ('carb_total_g', models.FloatField(default=0)),
                ('fat_total_g', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Intake',
        ),
    ]
