# Generated by Django 5.2.6 on 2025-09-18 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_food_meal_mealitem_nutritionlog_delete_intake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': '음식', 'verbose_name_plural': '음식 목록'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': '식사', 'verbose_name_plural': '식사 목록'},
        ),
        migrations.AlterModelOptions(
            name='mealitem',
            options={'verbose_name': '식사 항목', 'verbose_name_plural': '식사 항목 목록'},
        ),
        migrations.AlterField(
            model_name='food',
            name='carb_g_per_100g',
            field=models.FloatField(verbose_name='Carb G Per 100g'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_g_per_100g',
            field=models.FloatField(verbose_name='지방 G Per 100g'),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal_per_100g',
            field=models.FloatField(verbose_name='Kcal Per 100g'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_g_per_100g',
            field=models.FloatField(verbose_name='단백질 G Per 100g'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='log_date',
            field=models.DateField(verbose_name='Log 날짜'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁'), ('간식', '간식')], max_length=10, verbose_name='식사 유형'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='carb_g',
            field=models.FloatField(blank=True, null=True, verbose_name='Carb G'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='fat_g',
            field=models.FloatField(blank=True, null=True, verbose_name='지방 G'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.food', verbose_name='음식'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='grams',
            field=models.FloatField(blank=True, null=True, verbose_name='Grams'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='kcal',
            field=models.FloatField(blank=True, null=True, verbose_name='Kcal'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intake.meal', verbose_name='식사'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='protein_g',
            field=models.FloatField(blank=True, null=True, verbose_name='단백질 G'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='carb_total_g',
            field=models.FloatField(default=0, verbose_name='Carb Total G'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='fat_total_g',
            field=models.FloatField(default=0, verbose_name='지방 Total G'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='kcal_total',
            field=models.FloatField(default=0, verbose_name='Kcal Total'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='protein_total_g',
            field=models.FloatField(default=0, verbose_name='단백질 Total G'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
