# Generated by Django 5.2.6 on 2025-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_alter_food_options_alter_meal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionlog',
            options={'verbose_name': '영양 기록', 'verbose_name_plural': '영양 기록 목록'},
        ),
        migrations.AlterField(
            model_name='food',
            name='carb_g_per_100g',
            field=models.FloatField(verbose_name='탄수화물(g/100g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_g_per_100g',
            field=models.FloatField(verbose_name='지방(g/100g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal_per_100g',
            field=models.FloatField(verbose_name='열량(kcal/100g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_g_per_100g',
            field=models.FloatField(verbose_name='단백질(g/100g)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='log_date',
            field=models.DateField(verbose_name='기록 날짜'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='carb_g',
            field=models.FloatField(blank=True, null=True, verbose_name='탄수화물(g)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='fat_g',
            field=models.FloatField(blank=True, null=True, verbose_name='지방(g)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='grams',
            field=models.FloatField(blank=True, null=True, verbose_name='중량(g)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='kcal',
            field=models.FloatField(blank=True, null=True, verbose_name='열량(kcal)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='protein_g',
            field=models.FloatField(blank=True, null=True, verbose_name='단백질(g)'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='carb_total_g',
            field=models.FloatField(default=0, verbose_name='총 탄수화물(g)'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='fat_total_g',
            field=models.FloatField(default=0, verbose_name='총 지방(g)'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='kcal_total',
            field=models.FloatField(default=0, verbose_name='총 열량(kcal)'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='protein_total_g',
            field=models.FloatField(default=0, verbose_name='총 단백질(g)'),
        ),
    ]
