# Generated by Django 5.2.6 on 2025-09-18 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_weight_kg',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='weekly_sessions',
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kcal_target', models.IntegerField(blank=True, null=True)),
                ('protein_target_g', models.IntegerField(blank=True, null=True)),
                ('workout_minutes_target', models.IntegerField(blank=True, null=True)),
                ('completion_score', models.FloatField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_sessions', models.IntegerField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress', to='users.user')),
            ],
        ),
    ]
