# Generated by Django 5.2.6 on 2025-09-18 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_remove_goal_created_at_remove_goal_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailygoal',
            options={'verbose_name': '일일 목표', 'verbose_name_plural': '일일 목표 목록'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': '목표', 'verbose_name_plural': '목표 목록'},
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='completion_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Completion 점수'),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to='goals.goal', verbose_name='목표'),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='kcal_target',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kcal Target'),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='protein_target_g',
            field=models.IntegerField(blank=True, null=True, verbose_name='단백질 Target G'),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='workout_minutes_target',
            field=models.IntegerField(blank=True, null=True, verbose_name='Workout Minutes Target'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(max_length=20, verbose_name='목표 유형'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='completed_sessions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Completed Sessions'),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='goals.goal', verbose_name='목표'),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
