# Generated by Django 5.2.6 on 2025-09-18 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_dailygoal_options_alter_goal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailygoal',
            options={'ordering': ['-date', '-id'], 'verbose_name': '일일 목표', 'verbose_name_plural': '일일 목표 목록'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-id'], 'verbose_name': '목표', 'verbose_name_plural': '목표 목록'},
        ),
        migrations.AlterModelOptions(
            name='goalprogress',
            options={'ordering': ['-date', '-id'], 'verbose_name': '목표 진행도', 'verbose_name_plural': '목표 진행도 목록'},
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='completion_score',
            field=models.FloatField(blank=True, null=True, verbose_name='달성도 점수(%)'),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='kcal_target',
            field=models.IntegerField(blank=True, null=True, verbose_name='목표 열량(kcal)'),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='protein_target_g',
            field=models.IntegerField(blank=True, null=True, verbose_name='목표 단백질(g)'),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='workout_minutes_target',
            field=models.IntegerField(blank=True, null=True, verbose_name='목표 운동 시간(분)'),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='completed_sessions',
            field=models.IntegerField(blank=True, null=True, verbose_name='완료 세션 수'),
        ),
        migrations.AlterUniqueTogether(
            name='dailygoal',
            unique_together={('user', 'goal', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='goalprogress',
            unique_together={('user', 'goal', 'date')},
        ),
    ]
