# Generated by Django 5.2.6 on 2025-09-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedbacks', '0001_initial'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='daily_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='goals.dailygoal', verbose_name='연계 일일 목표'),
        ),
    ]
