# Generated by Django 5.2.6 on 2025-09-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_achievement_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=10),
        ),
    ]
