# Generated by Django 5.2.6 on 2025-10-14 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_initial'),
        ('goals', '0002_initial'),
        ('tasks', '0005_taskitem_completed_taskitem_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ('-achieved_at',), 'verbose_name': '달성도', 'verbose_name_plural': '달성도 목록'},
        ),
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ('-date', '-id'), 'verbose_name': '일간 리포트', 'verbose_name_plural': '일간 리포트 목록'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-created_at',), 'verbose_name': '피드백', 'verbose_name_plural': '피드백 목록'},
        ),
        migrations.AlterModelOptions(
            name='feedbackgenerationlog',
            options={'ordering': ('-created_at',), 'verbose_name': '피드백 생성 로그', 'verbose_name_plural': '피드백 생성 로그 목록'},
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['user', 'achieved_at'], name='ach_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', 'date'], name='dr_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user', 'created_at'], name='fb_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['daily_report'], name='fb_daily_report_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackgenerationlog',
            index=models.Index(fields=['feedback', 'created_at'], name='fgl_fb_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_report_per_user_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0.0), ('score__lte', 100.0)), _connector='OR'), name='dailyreport_score_range'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('ai_confidence__isnull', True), models.Q(('ai_confidence__gte', 0.0), ('ai_confidence__lte', 100.0)), _connector='OR'), name='feedback_ai_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('sentiment_score__isnull', True), models.Q(('sentiment_score__gte', -1.0), ('sentiment_score__lte', 1.0)), _connector='OR'), name='feedback_sentiment_range'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'ai')), fields=('daily_report', 'source'), name='uniq_ai_feedback_per_report'),
        ),
    ]
