# Generated by Django 5.2.6 on 2025-09-18 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_achievement_dailyreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': '달성도', 'verbose_name_plural': '달성도 목록'},
        ),
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'verbose_name': '일간 리포트', 'verbose_name_plural': '일간 리포트 목록'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '피드백', 'verbose_name_plural': '피드백 목록'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achieved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Achieved At'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='mood',
            field=models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('bad', 'Bad')], default='average', max_length=20, verbose_name='Mood'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
