# Generated by Django 5.2.6 on 2025-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_alter_achievement_options_alter_dailyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achieved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='달성 시각'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='mood',
            field=models.CharField(choices=[('good', '좋음'), ('average', '보통'), ('bad', '나쁨')], default='average', max_length=20, verbose_name='기분'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='summary',
            field=models.TextField(blank=True, verbose_name='요약'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='메시지'),
        ),
    ]
