# Generated by Django 5.2.6 on 2025-09-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('kcal_burned_per_min', models.FloatField(default=0.0, verbose_name='분당 소모 칼로리')),
            ],
            options={
                'verbose_name': '운동',
                'verbose_name_plural': '운동 목록',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('summary', models.TextField(blank=True, verbose_name='요약')),
                ('target_focus', models.CharField(blank=True, max_length=50, verbose_name='중점 영역')),
                ('personalization_snapshot', models.JSONField(blank=True, help_text='생성 시점의 체중/BMI/활동량 등 사용자 상태', null=True, verbose_name='개인화 지표')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_initial', 'AI Initial'), ('ai_update', 'AI Update')], default='manual', max_length=20, verbose_name='생성 출처')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='AI 모델')),
                ('ai_version', models.CharField(blank=True, max_length=50, verbose_name='AI 버전')),
                ('ai_prompt', models.TextField(blank=True, verbose_name='AI 프롬프트')),
                ('ai_response', models.JSONField(blank=True, null=True, verbose_name='AI 응답')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='AI 신뢰도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='AI 마지막 동기화')),
            ],
            options={
                'verbose_name': '운동 계획',
                'verbose_name_plural': '운동 계획 목록',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlanGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(max_length=100, verbose_name='AI 모델')),
                ('ai_version', models.CharField(blank=True, max_length=50, verbose_name='AI 버전')),
                ('prompt', models.TextField(verbose_name='프롬프트')),
                ('response', models.JSONField(verbose_name='응답')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '운동 계획 생성 로그',
                'verbose_name_plural': '운동 계획 생성 로그 목록',
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_min', models.PositiveIntegerField(default=0, verbose_name='운동 시간(분)')),
                ('target_sets', models.PositiveIntegerField(blank=True, null=True, verbose_name='목표 세트')),
                ('target_reps', models.PositiveIntegerField(blank=True, null=True, verbose_name='목표 횟수')),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='강도')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('is_ai_recommended', models.BooleanField(default=False, verbose_name='AI 추천 여부')),
                ('ai_goal', models.CharField(blank=True, max_length=100, verbose_name='AI 설정 목표')),
                ('ai_metadata', models.JSONField(blank=True, null=True, verbose_name='AI 메타데이터')),
                ('recommended_weight_range', models.CharField(blank=True, max_length=50, verbose_name='권장 체중 범위')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='순서')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='tasks.exercise', verbose_name='운동')),
            ],
            options={
                'verbose_name': '작업 항목',
                'verbose_name_plural': '작업 항목 목록',
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('duration_min', models.PositiveIntegerField(default=0, verbose_name='운동 시간(분)')),
                ('kcal_burned', models.FloatField(default=0.0, verbose_name='소모 칼로리')),
                ('perceived_exertion', models.PositiveIntegerField(blank=True, null=True, verbose_name='체감 강도')),
                ('ai_adjusted', models.BooleanField(default=False, verbose_name='AI 조정 여부')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.exercise', verbose_name='운동')),
                ('task_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_logs', to='tasks.taskitem', verbose_name='연계 작업')),
            ],
            options={
                'verbose_name': '운동 기록',
                'verbose_name_plural': '운동 기록 목록',
            },
        ),
    ]
