# Generated by Django 5.2.6 on 2025-09-23 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='이름')),
                ('kcal_per_100g', models.FloatField(verbose_name='열량(kcal/100g)')),
                ('protein_g_per_100g', models.FloatField(verbose_name='단백질(g/100g)')),
                ('carb_g_per_100g', models.FloatField(verbose_name='탄수화물(g/100g)')),
                ('fat_g_per_100g', models.FloatField(verbose_name='지방(g/100g)')),
            ],
            options={
                'verbose_name': '음식',
                'verbose_name_plural': '음식 목록',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='기록 날짜')),
                ('meal_type', models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁'), ('간식', '간식')], max_length=10, verbose_name='식사 유형')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '식사',
                'verbose_name_plural': '식사 목록',
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField(blank=True, null=True, verbose_name='중량(g)')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='이름')),
                ('kcal', models.FloatField(blank=True, null=True, verbose_name='열량(kcal)')),
                ('protein_g', models.FloatField(blank=True, null=True, verbose_name='단백질(g)')),
                ('carb_g', models.FloatField(blank=True, null=True, verbose_name='탄수화물(g)')),
                ('fat_g', models.FloatField(blank=True, null=True, verbose_name='지방(g)')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intakes.food', verbose_name='음식')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intakes.meal', verbose_name='식사')),
            ],
            options={
                'verbose_name': '식사 항목',
                'verbose_name_plural': '식사 항목 목록',
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('kcal_total', models.FloatField(default=0, verbose_name='총 열량(kcal)')),
                ('protein_total_g', models.FloatField(default=0, verbose_name='총 단백질(g)')),
                ('carb_total_g', models.FloatField(default=0, verbose_name='총 탄수화물(g)')),
                ('fat_total_g', models.FloatField(default=0, verbose_name='총 지방(g)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '영양 기록',
                'verbose_name_plural': '영양 기록 목록',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
