# Generated by Django 5.2.7 on 2025-10-20 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ai_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='meals/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='serving_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='source',
            field=models.CharField(default='csv', max_length=20),
        ),
    ]
