# Generated by Django 5.2.6 on 2025-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('kcal_target', models.IntegerField(blank=True, null=True, verbose_name='목표 열량(kcal)')),
                ('protein_target_g', models.IntegerField(blank=True, null=True, verbose_name='목표 단백질(g)')),
                ('workout_minutes_target', models.IntegerField(blank=True, null=True, verbose_name='목표 운동 시간(분)')),
                ('completion_score', models.FloatField(blank=True, null=True, verbose_name='달성도 점수(%)')),
            ],
            options={
                'verbose_name': '일일 목표',
                'verbose_name_plural': '일일 목표 목록',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(max_length=20, verbose_name='목표 유형')),
            ],
            options={
                'verbose_name': '목표',
                'verbose_name_plural': '목표 목록',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('completed_sessions', models.IntegerField(blank=True, null=True, verbose_name='완료 세션 수')),
            ],
            options={
                'verbose_name': '목표 진행도',
                'verbose_name_plural': '목표 진행도 목록',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
