# Generated by Django 5.2.6 on 2025-09-19 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to='goals.goal', verbose_name='목표'),
        ),
        migrations.AddField(
            model_name='goalprogress',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='goals.goal', verbose_name='목표'),
        ),
        migrations.AddField(
            model_name='goalprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterUniqueTogether(
            name='dailygoal',
            unique_together={('user', 'goal', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='goalprogress',
            unique_together={('user', 'goal', 'date')},
        ),
    ]
