# Generated by Django 5.2.6 on 2025-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='배지')),
                ('achieved_at', models.DateTimeField(auto_now_add=True, verbose_name='달성 시각')),
                ('shared_to_ai', models.BooleanField(default=False, verbose_name='AI 공유 여부')),
            ],
            options={
                'verbose_name': '달성도',
                'verbose_name_plural': '달성도 목록',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('summary', models.TextField(blank=True, verbose_name='요약')),
                ('highlights', models.TextField(blank=True, verbose_name='하이라이트')),
                ('challenges', models.TextField(blank=True, verbose_name='과제')),
                ('mood', models.CharField(choices=[('good', '좋음'), ('average', '보통'), ('bad', '나쁨')], default='average', max_length=20, verbose_name='기분')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='AI 점수')),
                ('source', models.CharField(choices=[('user', 'User'), ('device', 'Device'), ('ai', 'AI')], default='user', max_length=10, verbose_name='생성 출처')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='AI 모델')),
                ('ai_response', models.JSONField(blank=True, null=True, verbose_name='AI 응답')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '일간 리포트',
                'verbose_name_plural': '일간 리포트 목록',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='메시지')),
                ('summary', models.TextField(blank=True, verbose_name='요약')),
                ('recommended_action', models.TextField(blank=True, verbose_name='추천 조치')),
                ('sentiment_score', models.FloatField(blank=True, null=True, verbose_name='감성 점수')),
                ('source', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('hybrid', 'Hybrid')], default='user', max_length=10, verbose_name='생성 출처')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='AI 모델')),
                ('ai_version', models.CharField(blank=True, max_length=50, verbose_name='AI 버전')),
                ('ai_prompt', models.TextField(blank=True, verbose_name='AI 프롬프트')),
                ('ai_response', models.JSONField(blank=True, null=True, verbose_name='AI 응답')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='AI 신뢰도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '피드백',
                'verbose_name_plural': '피드백 목록',
            },
        ),
        migrations.CreateModel(
            name='FeedbackGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(max_length=100, verbose_name='AI 모델')),
                ('ai_version', models.CharField(blank=True, max_length=50, verbose_name='AI 버전')),
                ('prompt', models.TextField(verbose_name='프롬프트')),
                ('response', models.JSONField(verbose_name='응답')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '피드백 생성 로그',
                'verbose_name_plural': '피드백 생성 로그 목록',
            },
        ),
    ]
