# Generated by Django 5.2.6 on 2025-09-17 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.goal')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
