# Generated by Django 5.2.6 on 2025-09-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_exercise_taskitem_workoutlog_workoutplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='ai_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='reviewed_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
