# Generated by Django 5.2.6 on 2025-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='target',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='대상 부위'),
        ),
    ]
