# Generated by Django 5.2.6 on 2025-09-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_exercise_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='target',
            field=models.CharField(default='full', max_length=50, verbose_name='대상 부위'),
            preserve_default=False,
        ),
    ]
