# Generated by Django 5.2.6 on 2025-09-18 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_exercise_workoutlog_workoutplan_taskitem_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': '운동', 'verbose_name_plural': '운동 목록'},
        ),
        migrations.AlterModelOptions(
            name='taskitem',
            options={'verbose_name': '작업 항목', 'verbose_name_plural': '작업 항목 목록'},
        ),
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'verbose_name': '운동 기록', 'verbose_name_plural': '운동 기록 목록'},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'verbose_name': '운동 계획', 'verbose_name_plural': '운동 계획 목록'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='kcal_burned_per_min',
            field=models.FloatField(default=0.0, verbose_name='Kcal Burned Per Min'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='duration_min',
            field=models.PositiveIntegerField(default=0, verbose_name='지속 시간 Min'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='tasks.exercise', verbose_name='운동'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.workoutplan', verbose_name='운동 계획'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='duration_min',
            field=models.PositiveIntegerField(default=0, verbose_name='지속 시간 Min'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.exercise', verbose_name='운동'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='kcal_burned',
            field=models.FloatField(default=0.0, verbose_name='Kcal Burned'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
