# Generated by Django 5.2.6 on 2025-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_exercise_options_alter_taskitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='kcal_burned_per_min',
            field=models.FloatField(default=0.0, verbose_name='분당 소모 칼로리'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='duration_min',
            field=models.PositiveIntegerField(default=0, verbose_name='운동 시간(분)'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='duration_min',
            field=models.PositiveIntegerField(default=0, verbose_name='운동 시간(분)'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='kcal_burned',
            field=models.FloatField(default=0.0, verbose_name='소모 칼로리'),
        ),
    ]
