# Generated by Django 5.2.6 on 2025-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_exercise_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='완료 여부'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='완료 시각'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='skip_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='스킵 사유'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='skipped',
            field=models.BooleanField(default=False, verbose_name='스킵 여부'),
        ),
    ]
